echo "(rss"
echo "Axmlns:itunes http://www.itunes.com/dtds/podcast-1.0.dtd"
echo "Aversion 2.0"
echo "(channel"
echo "(title"
echo "-$("Zane Lowe Radio 1 Show Podcast")"
echo ")title"
echo "(link"
echo "-$("http://www.barnabycolby.com/zanelowepodcast/")"
echo ")link"
echo "(description"
echo "-A podcast allowing Zane Lowe's radio 1 shows to be downloaded and listened to on demand."
echo ")description"
echo "(lastBuildDate"
echo "-Sat, 20 Dec 2014 12:00:00 GMTd"
echo ")lastBuildDate"
echo "(image"
echo "(url"
echo "-$("http://www.barnabycolby.com/zanelowepodcast/podcastImage.jpg")"
echo ")url"
echo "(title"
echo "-$("Zane Lowe Radio 1 Show Podcast")"
echo ")title"
echo "(link"
echo "-$("http://www.barnabycolby.com/zanelowepodcast/")"
echo ")link"
echo ")image"
echo "(language"
echo "-en-gb"
echo ")language"
echo "C We don't want this podcast showing up in the podcast directory, so we'll attempt to block it at first "
echo "(itunes:block"
echo "-yes"
echo ")itunes:block"
echo "C Itunes channel tags "
echo "(itunes:author"
echo "-Barnaby Colby"
echo ")itunes:author"
echo "C Has a minimum size of 1400x1400 "
echo "(itunes:image"
echo "Ahref $(http://www.barnabycolby.com/zanelowepodcast/podcastImage.jpg)"
echo ")itunes:image"
